---
- name: Add official RabbitMQ GPG key.
  rpm_key:
    key: "https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc"
    state: present

- name: Install RabbitMQ from RabbitMQ Repository
  yum:
    name: "{{ rabbitmq_rpm_url }}"
    state: present

